version: "3.3"

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: .  # Ubicacion del directorio central donde Construira la Imagen
      dockerfile: Dockerfile.dev  # Dockerfile -> Parametros [ Dev o Prod ]
    volumes:
      - ./:/usr/src/app # Compara Path Local con Path de Contenedor Checa si hay cambios
      - /usr/src/app/node_modules # Checa si hay cambios
      - /usr/src/app/.next # Checa si hay cambios
    env_file:
      - .env # enviroments si no lo tiene tu proyecto creealo para que funcione