name: Dockerize and Pushing Docker Hub
on: push
jobs:
  build-container:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses:  actions/checkout@v1
      - name: Publish to GithubPackages
        uses: docker/build-push-action@v2.4
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/next
          tags: latest, ${{ github.run_number }}
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: katchvidal/next
          tags: latest, ${{ github.run_number }}

